spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: zhb
    password: zhb
    virtual-host: cloud-zhb
  sleuth:
    stream:
      enabled: false
    sampler:
      percentage: 0.1
eureka:
  instance:
    prefer-ip-address: true
    status-page-url: /info.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
